--- #YAML:1.0
name:                Time-Simple
version:             0.053
abstract:            A simple, light-weight ISO 8601 time object.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Lee Goddard <lgoddard-at-cpan-dot-org>
